# Generated by Django 3.0.8 on 2021-08-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_user_email_extension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoemailverifier',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
