name: Python package

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=venv
    - name: Test with unittest
      run: |
        pip install -r requirements.txt
        python manage.py makemigrations && coverage run runtests.py

        # generate coverage json report
        coverage json
        # just print coverage locally
        coverage report --fail-under=70

    - name: Check distribution valid
      run: |
        pip install wheel twine
        python setup.py bdist_wheel
        twine check dist/*

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        ## secrets should have CODECOV_TOKEN
        #token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        name: codecov-django-user-email-extention
        fail_ci_if_error: true
        verbose: true